name: Auto Sync

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Sync with upstream
        run: |
          git fetch origin
          git pull origin main
          git push origin main
