name: Auto Sync

on:
  push:
    branches: [main]
  # schedule:
  #   - cron: "0 */6 * * *" # Runs every 6 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git add data/football.db
          git diff --quiet && git diff --staged --quiet || git commit -m "Update SQLite database"

      - name: Sync with upstream
        run: |
          git fetch origin
          git pull origin main
          git push origin main
