name: Data Sync

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC daily
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pandas requests beautifulsoup4

      - name: Create data directory
        run: mkdir -p data

      - name: Run sync script
        run: python football.py

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/football.db
          git commit -m "Update football database" || echo "No changes to commit"
          git push
